server:
  port: 8080
  servlet:
    context-path: /api

mybatis:
  mapper-locations: classpath:github/runoob09/mapper/*.xml
  type-aliases-package: github.runoob09.entity

mybatis-plus:
  global-config:
    db-config:
      id-type: ASSIGN_ID

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center
    username: root
    password: 20020725
    driver-class-name: com.mysql.cj.jdbc.Driver
